name: CI

on:
  push:
    branches: ["main", "dev", "feature/**"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install fastapi "uvicorn[standard]" pytest httpx

      - name: Run pytest
        run: pytest -q

      - name: Upload coverage (optional)
        if: success()
        uses: codecov/codecov-action@v4
