name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          pip install -r requirements.txt
          pytest -q

  deploy:
    needs: test          # виконується ТІЛЬКИ якщо job "test" зелений
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'   # деплой лишень із гілки main
    steps:
      - name: Trigger Render deploy
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
